version: '2.4'
services:
  prescription-database:
    container_name: 'prescription-database'
    image: postgres:14.2-alpine
    hostname: prescription-database
    mem_limit: 300m
    memswap_limit: 1100m
    ports:
      - 15432:5432
    volumes:
     - ./db/data:/var/lib/postgresql/data
     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      POSTGRES_USER: prescription_user
      POSTGRES_PASSWORD: prescription_pw